name: dul
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab
  - ipython
  - matplotlib
  - pandas
  - scikit-learn
  - scipy
  - numpy
  - torchvision
  - pytorch
  - cudatoolkit=11.3
  - torchdiffeq
  - opencv
